const listings = [
  {
    title: "Peace Heaven Karnatak",
    description: "Clean single room for students preparing for exams. Peaceful locality.",
    location: "Tarnaka, Hyderabad",
    country: "India",
    price: 5500,
    electricityCost: 500,
    maintenanceCost: 300,
    depositAmount: 5500,
    trueMonthlyCost: 6300,
    foodIncluded: false,
    wifiAvailable: true,
    roomType: "single",
    genderPreference: "unisex",
    image: { url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60", filename: "default-listing-image" }
  },
  {
    title: "Annupam Co Living PG",
    description: "Very close to metro station. Double bed setup with independent bath. Daily meals included.",
    location: "Miyapur Metro, Hyderabad",
    country: "India",
    price: 6000,
    electricityCost: 500,
    maintenanceCost: 350,
    depositAmount: 6500,
    trueMonthlyCost: 6850,
    foodIncluded: true,
    wifiAvailable: true,
    roomType: "double",
    genderPreference: "boys",
    image: { url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=800&q=60", filename: "default-listing-image" }
  },
  {
    title: "Banjara Heights Women's PG",
    description: "Secure PG for working women with personal wardrobes, washing machine, and great connectivity.",
    location: "Banjara Hills, Hyderabad",
    country: "India",
    price: 12500,
    electricityCost: 900,
    maintenanceCost: 800,
    depositAmount: 15000,
    trueMonthlyCost: 14200,
    foodIncluded: true,
    wifiAvailable: true,
    roomType: "double",
    genderPreference: "girls",
    image: { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60", filename: "default-listing-image" }
  },
  {
    title: "Tech Nest Miyapur",
    description: "Single occupancy space perfect for focused work. High speed wifi included. No food.",
    location: "Miyapur, Hyderabad",
    country: "India",
    price: 8000,
    electricityCost: 600,
    maintenanceCost: 400,
    depositAmount: 8500,
    trueMonthlyCost: 9000,
    foodIncluded: false,
    wifiAvailable: true,
    roomType: "single",
    genderPreference: "unisex",
    image: { url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60", filename: "default-listing-image" }
  },
  {
    title: "Finestay HITEC City",
    description: "Bright single room with study desk, 200 Mbps wifi, and tiffin service. 8 min walk to HITEC metro.",
    location: "HITEC City, Hyderabad",
    country: "India",
    price: 5000,
    electricityCost: 600,
    maintenanceCost: 400,
    depositAmount: 6000,
    trueMonthlyCost: 6000,
    foodIncluded: true,
    wifiAvailable: true,
    roomType: "single",
    genderPreference: "unisex",
    image: { url: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?auto=format&fit=crop&w=800&q=60", filename: "default-listing-image" }
  },
  {
    title: "Madhav PG Madhapur",
    description: "Balcony room, daily breakfast+dinner, close to tech offices and cafes in Madhapur.",
    location: "Madhapur, Hyderabad",
    country: "India",
    price: 8500,
    electricityCost: 900,
    maintenanceCost: 600,
    depositAmount: 10000,
    trueMonthlyCost: 10000,
    foodIncluded: true,
    wifiAvailable: true,
    roomType: "double",
    genderPreference: "boys",
    image: { url: "https://images.unsplash.com/photo-1615874959375-5d4c00ba1416?auto=format&fit=crop&w=800&q=60", filename: "default-listing-image" }
  },
  {
    title: "Suresh PG Kondapur",
    description: "AC double sharing, homely meals, RO water, 24x7 power backup. 10 mins to Gachibowli flyover.",
    location: "Kondapur, Hyderabad",
    country: "India",
    price: 7500,
    electricityCost: 700,
    maintenanceCost: 500,
    depositAmount: 8500,
    trueMonthlyCost: 8700,
    foodIncluded: true,
    wifiAvailable: true,
    roomType: "double",
    genderPreference: "girls",
    image: { url: "https://images.unsplash.com/photo-1522708306214-c4b1b2915current?auto=format&fit=crop&w=800&q=60", filename: "default-listing-image" }
  },
  {
    title: "Smart Living SR Nagar",
    description: "Affordable triple sharing room with high-speed internet and locker facilities. Near coaching centers.",
    location: "SR Nagar, Hyderabad",
    country: "India",
    price: 4500,
    electricityCost: 400,
    maintenanceCost: 250,
    depositAmount: 4500,
    trueMonthlyCost: 5150,
    foodIncluded: false,
    wifiAvailable: true,
    roomType: "triple",
    genderPreference: "boys",
    image: { url: "https://images.unsplash.com/photo-1515221318891-4c4e40bb1bca?auto=format&fit=crop&w=800&q=60", filename: "default-listing-image" }
  },
  {
    title: "Royal Palace Jubilee Hills",
    description: "Fully furnished studio for singles with gym access, pool, and fine dining nearby.",
    location: "Jubilee Hills, Hyderabad",
    country: "India",
    price: 16000,
    electricityCost: 1500,
    maintenanceCost: 1200,
    depositAmount: 25000,
    trueMonthlyCost: 18700,
    foodIncluded: false,
    wifiAvailable: true,
    roomType: "single",
    genderPreference: "unisex",
    image: { url: "https://images.unsplash.com/photo-1631049307038-da8ec3ff3b68?auto=format&fit=crop&w=800&q=60", filename: "default-listing-image" }
  },
  {
    title: "Scholar's Haven Kukatpally",
    description: "Walkable from JNTU college. Nutritious food, strict security, and laundry facilities included.",
    location: "Kukatpally JNTU, Hyderabad",
    country: "India",
    price: 6000,
    electricityCost: 600,
    maintenanceCost: 300,
    depositAmount: 6500,
    trueMonthlyCost: 6900,
    foodIncluded: true,
    wifiAvailable: true,
    roomType: "triple",
    genderPreference: "girls",
    image: { url: "https://images.unsplash.com/photo-1565182999555-b12d5eb38924?auto=format&fit=crop&w=800&q=60", filename: "default-listing-image" }
  },
  {
    title: "Gachibowli Corporate Stay",
    description: "Luxury double sharing setup for IT professionals. Includes smart TV, AC, and daily housekeeping.",
    location: "Gachibowli / Nanakramguda, Hyderabad",
    country: "India",
    price: 11000,
    electricityCost: 1000,
    maintenanceCost: 700,
    depositAmount: 12000,
    trueMonthlyCost: 12700,
    foodIncluded: true,
    wifiAvailable: true,
    roomType: "double",
    genderPreference: "boys",
    image: { url: "https://images.unsplash.com/photo-1543269865-cbdf26cecbb1?auto=format&fit=crop&w=800&q=60", filename: "default-listing-image" }
  },
  {
    title: "Ameerpet ColiveSpace",
    description: "Four-sharing room ideal for students attending software courses. Cheap and best. Co-living space.",
    location: "Ameerpet, Hyderabad",
    country: "India",
    price: 4800,
    electricityCost: 350,
    maintenanceCost: 150,
    depositAmount: 3500,
    trueMonthlyCost: 5300,
    foodIncluded: true,
    wifiAvailable: false,
    roomType: "triple",
    genderPreference: "unisex",
    image: { url: "https://images.unsplash.com/photo-1455849318169-8e9e0f8c5e8a?auto=format&fit=crop&w=800&q=60", filename: "default-listing-image" }
  },
  {
    title: "Kphb Friends Living",
    description: "Triple sharing with simple amenities. Suitable for students. High speed WiFi included.",
    location: "KPHB Colony, Hyderabad",
    country: "India",
    price: 5200,
    electricityCost: 400,
    maintenanceCost: 180,
    depositAmount: 4500,
    trueMonthlyCost: 5780,
    foodIncluded: true,
    wifiAvailable: true,
    roomType: "triple",
    genderPreference: "girls",
    image: { url: "https://images.unsplash.com/photo-1540932549986-b8899649aad4?auto=format&fit=crop&w=800&q=60", filename: "default-listing-image" }
  },
  {
    title: "Mehdipatnam Comfort Hub",
    description: "Homely PG catering to specific dietary preferences. Spacious rooms with 24x7 WiFi.",
    location: "Mehdipatnam, Hyderabad",
    country: "India",
    price: 7200,
    electricityCost: 550,
    maintenanceCost: 350,
    depositAmount: 6500,
    trueMonthlyCost: 8100,
    foodIncluded: true,
    wifiAvailable: true,
    roomType: "double",
    genderPreference: "boys",
    image: { url: "https://images.unsplash.com/photo-1516132006556-38246b137277?auto=format&fit=crop&w=800&q=60", filename: "default-listing-image" }
  }
];

const reviews = [
  {
    comment: "Excellent! Clean rooms, responsive owner, great WiFi. Highly recommended.",
    foodQuality: 5,
    cleanliness: 5,
    wifi: 5,
    noise: 2,
    safety: 5,
    ownerBehavior: 5,
    rating: 5,
    compositeScore: 4.8
  },
  {
    comment: "Perfect for IT professionals. High-speed internet, peaceful environment.",
    foodQuality: 4,
    cleanliness: 5,
    wifi: 5,
    noise: 2,
    safety: 5,
    ownerBehavior: 5,
    rating: 5,
    compositeScore: 4.7
  },
  {
    comment: "Very good location near metro. Room is spacious and well-maintained.",
    foodQuality: 4,
    cleanliness: 5,
    wifi: 4,
    noise: 3,
    safety: 5,
    ownerBehavior: 4,
    rating: 4.5,
    compositeScore: 4.3
  },
  {
    comment: "Great value for money! Clean rooms and food quality is decent.",
    foodQuality: 4,
    cleanliness: 4,
    wifi: 5,
    noise: 3,
    safety: 5,
    ownerBehavior: 4,
    rating: 4.3,
    compositeScore: 4.2
  },
  {
    comment: "Budget-friendly option. Basic amenities but value is good.",
    foodQuality: 3,
    cleanliness: 3,
    wifi: 4,
    noise: 3,
    safety: 4,
    ownerBehavior: 4,
    rating: 3.5,
    compositeScore: 3.5
  },
  {
    comment: "Excellent food, very hygienic. Owner is attentive to issues.",
    foodQuality: 5,
    cleanliness: 5,
    wifi: 4,
    noise: 3,
    safety: 5,
    ownerBehavior: 5,
    rating: 4.8,
    compositeScore: 4.6
  },
  {
    comment: "Good for students. Affordable rent with decent facilities.",
    foodQuality: 3,
    cleanliness: 4,
    wifi: 4,
    noise: 2,
    safety: 5,
    ownerBehavior: 4,
    rating: 4.2,
    compositeScore: 3.9
  },
  {
    comment: "Premium experience! Everything is well-maintained and owner is friendly.",
    foodQuality: 5,
    cleanliness: 5,
    wifi: 5,
    noise: 2,
    safety: 5,
    ownerBehavior: 5,
    rating: 5,
    compositeScore: 4.9
  },
  {
    comment: "Location is perfect. Metro nearby, surrounded by restaurants.",
    foodQuality: 4,
    cleanliness: 5,
    wifi: 5,
    noise: 4,
    safety: 5,
    ownerBehavior: 4,
    rating: 4.5,
    compositeScore: 4.5
  },
  {
    comment: "Average PG. Basic facilities but management is good.",
    foodQuality: 2,
    cleanliness: 3,
    wifi: 3,
    noise: 4,
    safety: 4,
    ownerBehavior: 3,
    rating: 3,
    compositeScore: 3.2
  }
];

const users = [
  {
    username: "john_doe_hyd",
    email: "john.doe@example.com",
    password: "student123",
    userType: "student",
    phoneVerified: true
  },
  {
    username: "priya_sharma",
    email: "priya.sharma@example.com",
    password: "professional123",
    userType: "working-professional",
    phoneVerified: true
  },
  {
    username: "rahul_techie",
    email: "rahul.techie@example.com",
    password: "student123",
    userType: "student",
    phoneVerified: true
  },
  {
    username: "apartment_owner",
    email: "owner@roomradar.com",
    password: "host123",
    userType: "host",
    phoneVerified: true
  },
  {
    username: "admin_user",
    email: "admin@roomradar.com",
    password: "admin123",
    userType: "admin",
    phoneVerified: true
  }
];

module.exports = { listings, reviews, users };
